module.exports = {
	path: {
		src: {
			html: ['*.html'],
			htmlProd: ['*.html'],
			js: 'js/*.js',
			jsProd: ['js/*.js', '!js/*.min.js'],
			jsMinProd: 'js/*.min.js',
			jsDev: 'dev/development.js',
			style: 'scss/*.scss',
			styleCss: 'scss/*.css',
			styleProd: 'scss/*.scss',
			styleDev: 'dev/development.scss',
			img: ['img/**/*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)',
				'!img/wp*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)'],
			imgTrash: ['img/wp*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)'],
			imgProd: ['img/**/*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)',
				'!img/wp*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)',
				'!img/uno*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)'],
			imgProdUnoptimized: ['img/uno*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)'],
			imgProdTrash: ['img/wp*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)'],
			fonts: 'fonts/**/*.+(otf|eot|woff2|woff|ttf|svg|OTF|EOT|WOFF2|WOFF|TTF|SVG)',
			other: 'other/**/*.*',
		},
		build: {
			html: 'build',
			js: 'build/assets/js/',
			css: 'build/assets/css/',
			styleCss: 'build/assets/css/',
			img: 'build/assets/img/',
			imgTrash: 'build/content-images/',
			fonts: 'build/assets/fonts/',
			serve: 'build/',
			serveIndex: 'build/home.html',
			other: 'build/assets/other',
		},
		production: {
			html: '../',
			js: '../assets/js/',
			css: '../assets/css/',
			styleCss: '../assets/css',
			img: '../assets/img/',
			imgTrash: '../content-images/',
			fonts: '../assets/fonts/',
			serve: '../',
			serveIndex: 'home.html',
			other: '../assets/other',
		},
		watch: {
			html: ['*.html', 'template/**/*.html'],
			js: ['js/**/*.js'],
			style: ['scss/**/*.+(scss|sass)'],
			styleCss: 'scss/*.css',
			img: 'img/**/*.+(jpg|jpeg|png|svg|gif|ico|JPG|JPEG|PNG|SVG|GIF|ICO)',
			fonts: 'fonts/**/*.+(otf|eot|woff2|woff|ttf|svg|OTF|EOT|WOFF2|WOFF|TTF|SVG)',
			dev: 'dev/**/*.*',
		},
		scrennPage: '../01-home.html',
		clean: ['!build', 'build/*.*', 'build/assets/**', 'build/content-images/**'],
		cleanProd: ['../assets/**', '../content-images/**', '../*.html', '../assets/css/**/*.*', '!../index.html', '!../assets', '!../assets/css', '!../assets/css/style-wp.css'],

	}
};